version: '3.7'
services:
    hackit:
        build: hackIT
        ports:
            - 8000:8000
        volumes:
            - /usr/src/app/target
            - ./hackIT:/usr/src/app
        
    postgresql:
        build: hackIT_db/.
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - postgresql
