[package]
name = "hack-it"
version = "0.1.0"
authors = ["Joakim Anderlind <joakimanderlind@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-files = "0.2.1"
actix = "0.9.0"

tokio-postgres = "0.5.4"
env_logger = "0.7"
log = "0.4.8"
